spring.application.name=complainttracker
spring.datasource.url=jdbc:mysql://localhost:3306/complaint_db
spring.datasource.username=root
spring.datasource.password=Neha2805

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true